In [4]:
import numpy as np
%config Completer.use_jedi = False

In [120]:
np.sum(np.where(result==0,1,0)), np.sum(np.where(result==1,1,0))

(7, 3)

In [247]:
# numbers=np.arange(1,46)

r=np.arange(1,45)
s=7
pick_cnt=10
weeks=54*100
win=0
semi_win=0
zer,one,two,thr,fou,fiv=0,0,0,0,0,0
paid=0

# 1년(54주)동안 10개씩 
for week in range(1,weeks):
    paid+=10000
    buy_lot=[np.random.choice(r, size=s, replace=False) for i in range(pick_cnt)]
    winning_number=np.random.choice(r, size=s, replace=False)
    result=np.array([14-len(Counter(np.concatenate([lot, winning_number]))) for lot in buy_lot])
    
#     print("buy lot :", buy_lot)
#     print("winning number : ", winning_number)
#     print(result)
    
    zer+=np.sum(np.where(result==0,1,0))
    one+=np.sum(np.where(result==1,1,0))
    two+=np.sum(np.where(result==2,1,0))
    thr+=np.sum(np.where(result==3,1,0))
    fou+=np.sum(np.where(result==4,1,0))
    fiv+=np.sum(np.where(result==5,1,0))
    
    upper5=np.argwhere(result>=6)
    if len(upper5)>0:
        for idx in upper5:
            w1=buy_lot[idx[0]][:6]
            a =winning_number[:6]
            if len(Counter(np.concatenate([w1,a]))) == 6:
                win+=1
                break
            else:
                semi_win+=1
        break
#     break
print(f"total years : {(weeks*7)/365}")
print(f"paid Money : {paid}")

print(f"0 : {zer}\n1 : {one}\n2 : {two}\n3 : {thr}\n4 : {fou}\n5 : {fiv}")
print(f"semi-win : {semi_win}\nwin : {win}")

total years : 103.56164383561644
paid Money : 53350000
0 : 14202
1 : 22700
2 : 12842
3 : 3204
4 : 384
5 : 17
semi-win : 1
win : 0

In [253]:
# numbers=np.arange(1,46)

r=np.arange(1,45)
s=7
pick_cnt=10
# weeks=54*100
weeks=0
win,semi_win=0,0
zer,one,two,thr,fou,fiv=0,0,0,0,0,0
paid=0

# 1년(54주)동안 10개씩 
while win == 0:
    weeks+=1
    paid+=pick_cnt*1000
    buy_lot=[np.random.choice(r, size=s, replace=False) for i in range(pick_cnt)]
    winning_number=np.random.choice(r, size=s, replace=False)
    result=np.array([14-len(Counter(np.concatenate([lot, winning_number]))) for lot in buy_lot])
    
#     print("buy lot :", buy_lot)
#     print("winning number : ", winning_number)
#     print(result)
    
    zer+=np.sum(np.where(result==0,1,0))
    one+=np.sum(np.where(result==1,1,0))
    two+=np.sum(np.where(result==2,1,0))
    thr+=np.sum(np.where(result==3,1,0))
    fou+=np.sum(np.where(result==4,1,0))
    fiv+=np.sum(np.where(result==5,1,0))
    
    upper5=np.argwhere(result>=6)
    if len(upper5)>0:
        for idx in upper5:
            w1=buy_lot[idx[0]][:6]
            a =winning_number[:6]
            if len(Counter(np.concatenate([w1,a]))) == 6:
                win+=1
                break
            else:
                semi_win+=1
                
print(f"total years : {(weeks*7)/365}")
print(f"paid Money : {paid}")

print(f"0 : {zer}\n1 : {one}\n2 : {two}\n3 : {thr}\n4 : {fou}\n5 : {fiv}")
print(f"semi-win : {semi_win}\nwin : {win}")

total years : 11575.4301369863
paid Money : 6035760000
0 : 1622342
1 : 2564165
2 : 1440030
3 : 364188
4 : 42829
5 : 2170
semi-win : 35
win : 1

In [262]:
result

array([1, 2, 1, 1, 1, 1, 0, 6, 2, 0])

In [221]:
for lot in buy_lot:
    print("lot : ".rjust(17),lot)
    print("winning_number : ",winning_number)
    print(np.sum(np.where((lot - winning_number==0),1,0)))

           lot :  [38  4  6 17 31  3  5]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [41 14 26  3 32 42 19]
winning_number :  [13 14 11 24 25 43 31]
1
           lot :  [42 44 22  8 19 18  6]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [15 10 20 21 42 30  6]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [28 15 35  6  2 27  7]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [39 38 18 27 23 32 36]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [33  7  1 23  5  3 18]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [ 4  6  3 16  2 11  1]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [17 38 37 26 28  9  7]
winning_number :  [13 14 11 24 25 43 31]
0
           lot :  [18  7 15  1 37 32 25]
winning_number :  [13 14 11 24 25 43 31]
0

In [284]:
pd.DataFrame(dataset[0])

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,-0.706838,-0.302998,0.770310,0.288344,-0.183425,-0.952870,1.076062,0.439875,-0.977145,-0.630285,1.188313,-0.878039,-0.223307,-0.327983,1.142631,-0.853264,0.935129,-0.330421,0.423000,-4.394101
1,-2.115214,-0.192695,-1.629239,-1.028001,0.080459,0.515704,0.024550,-1.716509,-0.651676,-0.995756,-0.316648,1.955212,0.527396,-0.852355,0.434728,-0.060375,-0.086665,1.640344,-1.174419,-0.833486
2,0.278319,0.834646,-0.525850,0.213760,0.076629,-0.196958,-0.232528,1.782240,1.331830,0.381811,-0.886886,0.245389,3.052685,-1.043729,1.300640,0.400175,-1.570601,1.225839,0.940743,-0.946664
3,-1.040008,0.508607,0.780810,-0.795764,0.688939,0.198156,-0.451523,1.682780,-1.131571,-0.010918,0.308008,-0.369271,-0.588121,0.686811,1.557020,0.096411,0.987217,-0.131955,0.206155,1.266300
4,0.584551,2.566121,-0.545075,0.540515,-1.141099,0.431543,-2.568461,0.551829,1.411308,-1.860993,-1.316968,0.119881,-0.152935,0.181981,0.119910,-1.976622,-1.539176,0.971154,0.193416,0.743316
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.417118,-1.504560,-1.096329,-0.288467,-1.570809,-0.769025,-1.200904,1.337257,-1.433795,0.580454,0.859204,-0.888678,0.019331,0.527330,1.040224,0.392714,2.000564,-2.131007,0.954181,-2.249059
9996,-1.299083,-0.054125,2.718122,0.170962,-1.847731,-0.196160,-0.468174,0.128290,0.129608,0.732287,1.746705,1.293217,-0.455622,-0.075201,-0.605591,-1.332869,-0.725905,1.620446,-1.428093,0.889189
9997,-0.104905,-0.060077,-0.234220,-1.819708,1.165222,-0.599259,-1.461533,1.048923,1.455300,0.491905,-0.417303,1.183017,1.116454,-0.821098,0.268121,-1.161005,-1.892954,1.802479,1.024416,-1.384512
9998,1.373281,-0.987556,-1.428714,-0.956802,-0.556509,0.626020,0.378320,0.569272,0.066032,-1.678931,-0.450566,-1.090694,-0.058161,-0.885970,-0.397672,0.293589,0.509585,-1.478085,0.664884,-0.161188
9999,1.445602,-2.213818,1.428919,-0.246277,0.243460,1.286035,-0.578975,-1.131657,0.491700,-0.908049,-0.257992,-0.206345,0.209391,0.851090,-0.100163,0.062143,0.000416,-1.067465,1.567493,-0.348913

In [313]:
dataset[0][:,0]

array([-1.26659691, -1.05841332, -1.84775986, ...,  1.59175426,
       -0.95194476,  1.1665249 ])

In [358]:
dataset.groupby(by="y").X1.count()

y
0    30234
1    69766
Name: X1, dtype: int64

In [363]:
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import numpy as np
import pandas as pd

dataset=make_classification(n_samples=100000, n_features=3, n_informative=3, n_redundant=0, n_classes=2, weights=(0.18,0.82), flip_y=0)
dataset=pd.DataFrame(data={"X1":dataset[0][:,0],"X2":dataset[0][:,1],"X3":dataset[0][:,2], "y":dataset[1]})

X=dataset[["X1","X2","X3"]]
y=dataset.y

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

clfs=[(f"Dum{i}", DummyClassifier(strategy="stratified", )) for i in range(9)]

for n, clf in clfs:
    clf.fit(X_train, y_train)
    print(accuracy_score(clf.predict(X_test), y_test))    

vc=VotingClassifier(estimators=clfs, )

vc.fit(X_train, y_train)
print("Voting", accuracy_score(vc.predict(X_test), y_test))

0.69865
0.7071
0.70515
0.70625
0.7018
0.70335
0.70505
0.70635
0.70375
Voting 0.813

In [342]:
clfs

[DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform'),
 DummyClassifier(strategy='uniform')]